### PR TITLE
add Fverb

### PR DESCRIPTION
**Pull request by schollz**
Hi @madskjeldgaard, I have one more for your repo - the Fverb from [JP Cimalnado](https://github.com/jpcima/fverb). It is converted from Faust, so if that is out of bounds for this repo, no problem. But I do find this to be one of the most incredible sounding reverbs encountered for SuperCollider.

### CODE REVIEW

**Comment by madskjeldgaard** [comment]
This looks great Schollz. Thanks for another contribution! I wonder if we should add some information about how it was converted. The SuperCollider architecture sometimes changes in Faust and it has an effect on the generated output of a fast command. 

Maybe this should be added in the help file or something? Which command, which tool, which faust version etc ?

**Comment by schollz** [comment]
Great idea, will add!

**Comment by schollz** [comment]
I recompiled with the latest faust and added a script `convert.sh` with the method (using your `faust2sc.py`!).

This hasn't been tested on Windows. I have a Windows computer that I could use but I've never compiled SC code on Windows. Would you know of a tutorial for installing the SuperCollider toolchain on Windows?

**Comment by schollz** [comment]
I saw that you updated the build - all is working well now with this! I just force pushed the changes to keep it from conflicting with the new version.

**Comment by madskjeldgaard** [comment]
Thanks @schollz this works really well and has nice docs and sounds fantastic. I'll merge it now. Thank for another great contribution!

**Comment by schollz** [comment]
Thanks @madskjeldgaard !! When you get a chance, would you post a release? Id like to share this one with my mac-based friends using the builds from the pipeline

**Comment by madskjeldgaard** [comment]
Sure!

**Pull request merged**
