### PR TITLE
more Tape plugins

### PR DESCRIPTION
**Pull request by schollz**

### CODE REVIEW

**Comment by madskjeldgaard** [comment]
This looks fantastic @schollz. Let me test it out and report back to you! Thanks so much..

**Comment by madskjeldgaard** [comment]
Tried them now @schollz. Absolutely stellar work. They work really nicely. Thanks a lot! 

I just have a few questions for you to consider before we merge:

* Could you add the plugin names to the overview in the README.md file in the "Included plugins" section ? 
* Do you think any of the parameters need interpolation/smoothing? I'm not sure, and quick tests don't seem to point to a need for that but just want to ask to be sure if you think so (see "Interpolating control rate parameters" here if you are unsure what I mean: https://scsynth.org/t/tutorial-supercollider-server-plugins-in-c/3449) 
* Do you have any bigger examples for usage? The help files you wrote are nice and precise, I think, but if you happen to have cool code examples lying about you could add to the example section, that would be nice, but not a big deal if not. 

Thanks again for the great work!

**Comment by schollz** [comment]
Thanks @madskjeldgaard !

I completely forgot about the README! Yeah I was planning on fixing that up to.

I agree about better examples too... some of the fx are pretty subtle! I have way better examples from my own usage I can share.

Thanks for your link, I didn't know about your tutorial. It is astounding work. Re: smoothing, its a good idea. I removed it while debugging when something wasn't working and I erroneously thought it was the smoothing and then neglected to put it back!

Your feedback is greatly appreciated. I will follow up! Not sure when - maybe today, maybe next month... but please keep the PR open :)

**Comment by madskjeldgaard** [comment]
Thanks and again: excellent work !Sent from my iPhoneOn 26 Jan 2023, at 17.04, Zack ***@***.***> wrote:﻿
Thanks @madskjeldgaard !
I completely forgot about the README! Yeah I was planning on fixing that up to.
I agree about better examples too... some of the fx are pretty subtle! I have way better examples from my own usage I can share.
Thanks for your link, I didn't know about your tutorial. It is astounding work. Re: smoothing, its a good idea. I removed it while debugging when something wasn't working and I erroneously thought it was the smoothing and then neglected to put it back!
Your feedback is greatly appreciated. I will follow up! Not sure when - maybe today, maybe next month... but please keep the PR open :)

**Comment by madskjeldgaard** [comment]
Hey schollz - hope you are good. Any update on this? Really wanna get these wonderful plugins out!

**Comment by schollz** [comment]
Soon! I'm still thinking about it just haven't got a chance to sit at a computer long enough :)

**Comment by schollz** [comment]
I made it! Please have a look through - I added to the README and put better examples up. 

I decided not to filter the parameters - I wasn't getting any issues without filtering and realized that some of the parameters in the UGens are recalculated on change so filtering would add a cost to the CPU (more steps of recalculation).

Happy to still make adjustments, won't be so long next time :)

**Comment by madskjeldgaard** [comment]
> I made it! Please have a look through - I added to the README and put better examples up.
> 
> I decided not to filter the parameters - I wasn't getting any issues without filtering and realized that some of the parameters in the UGens are recalculated on change so filtering would add a cost to the CPU (more steps of recalculation).
> 
> Happy to still make adjustments, won't be so long next time :)

Looks excellent! I've used them for a bit now (and love them!!!) and haven't had any issues so it's probably fine. Thank you so much!

**Comment by schollz** [comment]
Whoa that was fast! Thanks :) I probably will be adding one more to your repo soon...

**Comment by madskjeldgaard** [comment]
> Whoa that was fast! Thanks :) I probably will be adding one more to your repo soon...

You are always welcome. I should contribute a bit more myself soon as well, thanks for the inspiration!

**Pull request merged**
